#!/usr/bin/env node
// Generate CATALOG.md, skills.sh.json, and refresh skills_index.json from skills/<id>/SKILL.md
const fs = require("fs");
const path = require("path");
const { parseFrontmatter } = require("./frontmatter");

const root = path.resolve(__dirname, "..", "..");
const skillsRoot = path.join(root, "skills");

const check = process.argv.includes("--check");
function writeGenerated(relativePath, contents) {
  const destination = path.join(root, relativePath);
  if (check) {
    const current = fs.existsSync(destination) ? fs.readFileSync(destination, "utf8") : "";
    if (current.replace(/\r\n/g, "\n") !== contents.replace(/\r\n/g, "\n")) {
      throw new Error(`${relativePath} is stale; run npm run index`);
    }
  } else {
    fs.writeFileSync(destination, contents);
  }
}

const index = [];
for (const dir of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
  if (!dir.isDirectory() || dir.name.startsWith(".")) continue;
  const skillPath = path.join(skillsRoot, dir.name, "SKILL.md");
  if (!fs.existsSync(skillPath)) continue;
  const text = fs.readFileSync(skillPath, "utf8");
  const { meta } = parseFrontmatter(text);
  const variants = {
    gpt: fs.existsSync(path.join(skillsRoot, dir.name, "gpt.md")),
    gemini: fs.existsSync(path.join(skillsRoot, dir.name, "gemini.md")),
  };
  index.push({
    id: meta.name || dir.name,
    path: "skills/" + dir.name,
    category: meta.category || "uncategorized",
    name: meta.name || dir.name,
    description: meta.description || "",
    risk: meta.risk || "safe",
    source: meta.source || "self",
    date_added: meta.date_added || "",
    tags: Array.isArray(meta.tags) ? meta.tags : [],
    tools: Array.isArray(meta.tools) ? meta.tools : [],
    variants,
  });
}

index.sort((a, b) => a.id.localeCompare(b.id));

fs.mkdirSync(path.join(root, "data"), { recursive: true });
writeGenerated(
  "skills_index.json",
  JSON.stringify(index, null, 2)
);
writeGenerated(
  "data/skills_index.json",
  JSON.stringify(index, null, 2)
);

const byCat = {};
for (const s of index) {
  if (!byCat[s.category]) byCat[s.category] = [];
  byCat[s.category].push(s);
}

const lines = [
  "# Major AI Skills Catalog",
  "",
  "> Generated registry of **" + index.length + "** installable skills.",
  "",
  "Use `skills_index.json` for machine-readable discovery. Each skill lives at `skills/<id>/SKILL.md`.",
  "",
  "Install an exact skill with the command beside it. The Vercel CLI prompts for the target agent; add `--agent codex` or `--agent claude-code` to choose explicitly. Installs default to the current project.",
  "",
  "[Featured workflows and reproducible examples](docs/users/spotlight.md) | [skills.sh repository](https://skills.sh/alivirgo/Major-AI-Skills)",
  "",
  "## Categories",
  "",
];

for (const cat of Object.keys(byCat).sort()) {
  lines.push("- [" + cat + "](#" + cat + ") - " + byCat[cat].length + " skills");
}
lines.push("");

for (const cat of Object.keys(byCat).sort()) {
  lines.push("## " + cat, "");
  lines.push("| Skill | Description | Install |");
  lines.push("| --- | --- | --- |");
  for (const s of byCat[cat].sort((a, b) => a.id.localeCompare(b.id))) {
    const desc = (s.description || "").replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
    lines.push("| [`" + s.id + "`](" + s.path + "/SKILL.md) | " + desc + " | `npx skills add alivirgo/Major-AI-Skills --skill " + s.id + "` |");
  }
  lines.push("");
}

writeGenerated("CATALOG.md", lines.join("\n"));
writeGenerated("catalog.html", require("./render_catalog").renderCatalog(index));
writeGenerated("assets/skill-catalog.js", "// Generated by npm run index.\nwindow.MAJOR_AI_SKILLS = " + JSON.stringify(index) + ";\n");
const lucideDirectory = path.resolve(path.dirname(require.resolve("lucide")), "../umd");
writeGenerated("assets/lucide.min.js", fs.readFileSync(path.join(lucideDirectory, "lucide.min.js"), "utf8").replace(/\/\/# sourceMappingURL=.*$/m, ""));
writeGenerated("assets/lucide-LICENSE", fs.readFileSync(path.resolve(lucideDirectory, "../../LICENSE"), "utf8"));

const spotlight = JSON.parse(fs.readFileSync(path.join(root, "data/spotlight.json"), "utf8"));
const spotlightIds = new Set();
for (const entry of spotlight) {
  if (!index.some(skill => skill.id === entry.id) || spotlightIds.has(entry.id)) {
    throw new Error(`Invalid or duplicate spotlight ID: ${entry.id}`);
  }
  spotlightIds.add(entry.id);
}
writeGenerated("assets/skill-spotlight.js", "// Generated by npm run index.\nwindow.MAJOR_AI_SPOTLIGHT = " + JSON.stringify(spotlight) + ";\n");
const showcase = [
  "# Featured Workflows",
  "",
  "Six focused ways to try Major AI Skills. Choose one that matches your work; each includes an exact install command, prerequisites, a prompt, and acceptance criteria.",
  "",
  "The portable FFmpeg, DuckDB, and Playwright examples are reference implementations with assertions. They test the demonstrated operations, not whether an AI model follows every skill instruction. Blender, Figma, and SOLIDWORKS are guided workflows requiring their respective applications. A passing reference is not a quality certification for the complete skill.",
  "",
  "## Run the portable references",
  "",
  "From a clone of this repository, with Node.js 22 or newer:",
  "",
  "```bash",
  "cd examples/spotlight",
  "npm ci",
  "npm run browser:install",
  "npm test",
  "```",
  "",
  "The runner creates a fresh directory under `examples/spotlight/output/` containing a JSON report, video files, a revenue CSV, browser screenshots, and traces. A failed check returns a nonzero exit code. Dependencies and browser binaries require network access during setup; reference workloads use local fixtures. See the [reference README](../../examples/spotlight/README.md) and [recorded verification](../../examples/spotlight/VERIFICATION.md).",
  "",
  "CLI installs below default to the current project and prompt for agent selection. Append `--agent codex` or `--agent claude-code` for an explicit target; use `-g` only for an intended global install. Installing a skill does not install its target application.",
  "",
];
for (const entry of spotlight) {
  const skill = index.find(skill => skill.id === entry.id);
  showcase.push(`## ${entry.id}`, "", `**${entry.title}**`, "", skill.description, "", entry.audience, "",
    `[Read the skill](../../skills/${entry.id}/SKILL.md) | [skills.sh page](https://skills.sh/alivirgo/Major-AI-Skills/${entry.id})`, "",
    "```bash", `npx skills add alivirgo/Major-AI-Skills --skill ${entry.id}`, "```", "",
    "### Prerequisites", "", ...entry.prerequisites.map(item => `- ${item}`), "",
    "### Try This Prompt", "", "```text", entry.prompt, "```", "",
    "### Expected Outputs", "", ...entry.outputs.map(item => `- ${item}`), "",
    "### Acceptance Checks", "", ...entry.checks.map(item => `- [ ] ${item}`), "",
    "### Verification Scope", "", entry.limitations, "");
}
writeGenerated("docs/users/spotlight.md", showcase.join("\n"));
const featuredTable = [
  "<!-- spotlight:start -->", "",
  "Pick a concrete task, inspect its instructions, and install only that skill. Each walkthrough includes prerequisites, a ready-to-use prompt, expected outputs, and acceptance checks.", "",
  "| Workflow | Install | Example coverage |", "| --- | --- | --- |",
  ...spotlight.map(entry => `| [${entry.title}](docs/users/spotlight.md#${entry.id}) | \`npx skills add alivirgo/Major-AI-Skills --skill ${entry.id}\` | ${entry.reference ? "Runnable local reference" : "Application walkthrough"} |`),
  "", "[Run the reference examples](examples/spotlight/README.md) | [Verification record](examples/spotlight/VERIFICATION.md) | [All skills and install commands](CATALOG.md)",
  "", "<!-- spotlight:end -->",
].join("\n");
const readme = fs.readFileSync(path.join(root, "README.md"), "utf8");
if (!readme.includes("<!-- spotlight:start -->") || !readme.includes("<!-- spotlight:end -->")) {
  throw new Error("README spotlight markers are missing");
}
writeGenerated("README.md", readme.replace(/<!-- spotlight:start -->[\s\S]*?<!-- spotlight:end -->/, featuredTable));

const titleCase = (value) =>
  value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const categoryPresentation = {
  "3d": ["3D & VFX", "Procedural scenes, modeling, texturing, and rendering."],
  automation: ["Workflow Automation", "Connect services with event-driven workflows and data mapping."],
  cad: ["CAD & Modeling", "Parametric parts, assemblies, geometry, and engineering exports."],
  "common-sense": ["Everyday AI Work", "Clear prompts, useful drafts, source checking, and practical decisions."],
  "cross-platform": ["Media & Utilities", "Media processing, API clients, transfers, and cross-platform tools."],
  design: ["Design Tools", "Design-system automation, image workflows, and asset exports."],
  development: ["Application Development", "Web, mobile, language, API, and application integration workflows."],
  devops: ["Cloud & DevOps", "Infrastructure, databases, CI, deployment, and observability."],
  "digital-forensics": ["Digital Forensics", "Authorized evidence processing and forensic software automation."],
  eda: ["Electronic Design", "PCB automation, circuit simulation, and verification workflows."],
  efficiency: ["Context & Efficiency", "Bounded context, concise output, repeatable edits, and measured resource use."],
  enterprise: ["Enterprise Platforms", "CRM, asset management, service operations, and PLM integrations."],
  erp: ["ERP Systems", "Enterprise business-system scripting and integration workflows."],
  "game-engines": ["Game Engines", "Editor automation, gameplay code, scenes, and build pipelines."],
  gis: ["GIS", "Geospatial processing, map data, and spatial automation."],
  knowledge: ["Knowledge Tools", "Notes, documents, pages, and knowledge-base organization."],
  linux: ["Linux Desktop", "Omarchy desktop configuration and customization."],
  macos: ["macOS Tools", "Desktop productivity, local automation, and application integrations."],
  medical: ["Imaging Software", "DICOM, visualization, and research-software workflows."],
  music: ["Music Production", "DAW scripting, MIDI, audio configuration, and session workflows."],
  network: ["Networking", "Controller configuration, connectivity, routing, and traffic inspection."],
  office: ["Office Automation", "Workbook scripting, data transformation, and spreadsheet workflows."],
  "plc-industrial": ["Industrial Automation", "PLC development and industrial software in authorized test environments."],
  productivity: ["Project Tools", "Tasks, issue tracking, project organization, and team workflows."],
  scientific: ["Data & Science", "Analytical SQL, scientific computing, notebooks, and machine learning."],
  testing: ["Browser Testing", "Playwright user journeys, diagnostics, and CI execution."],
  "video-editing": ["Video Production", "Timelines, compositions, interchange, and rendering workflows."],
  windows: ["Windows Tools", "Desktop scripting, diagnostics, capture, and utility configuration."],
};

const skillsShConfig = {
  $schema: "https://skills.sh/schemas/skills.sh.schema.json",
  notGrouped: "bottom",
  groupings: Object.keys(byCat)
    .sort()
    .map((cat) => ({
      title: categoryPresentation[cat]?.[0] || titleCase(cat),
      description: categoryPresentation[cat]?.[1] || `Major AI Skills for ${cat.replace(/[-_]/g, " ")} workflows.`,
      skills: byCat[cat].map((s) => s.id).sort((a, b) => a.localeCompare(b)),
    })),
};

writeGenerated(
  "skills.sh.json",
  JSON.stringify(skillsShConfig, null, 2) + "\n"
);

console.log(
  "Indexed " +
    index.length +
    " skills -> skills_index.json + CATALOG.md + skills.sh.json"
);
